; init

;; see early-init.el for gui pre-load options,
;; custom.el for autogenerated variables,
;; and packages.el for packages and configuration data.



(setq custom-file "~/.emacs.d/custom.el")
(load custom-file 'noerror)
(load-file "~/.emacs.d/packages.el")
