# generated by zsh first user installation
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -e

# generated by compinstall
zstyle :compinstall filename '/home/devin/.zshrc'
autoload -Uz compinit
compinit

#my additions (git vcs info, hostname, time, working directory)
autoload -Uz vcs_info
precmd() { vcs_info }
zstyle ':vcs_info:git:*' formats '%b '
setopt PROMPT_SUBST
PROMPT='%B%F{green}%n@%m%f%b %B%F{blue}%~%f%b %B%F{red}${vcs_info_msg_0_}%f%b> '

# custom aliases
alias ip='ip --color=auto'
alias ls='ls -lah --color=auto'
alias grep='grep --color=auto'
