# General Settings
gpu-api=vulkan
vo=gpu-next
hwdec=auto
vulkan-async-compute=yes
vulkan-async-transfer=yes
vulkan-queue-count=1
vd-lavc-dr=yes
no-hidpi-window-scale

# UI

border=no
msg-color=yes
#term-osd-bar=yes
force-window=immediate
cursor-autohide=1000 
macos-title-bar-appearance=vibrantDark
macos-title-bar-material=popover
macos-fs-animation-duration=0

# Color settings
target-prim=auto
# target-prim=bt.709 # target Rec.709 for SDR TVs
# target-prim=bt.2020 # target Rec.2020 (wide color gamut) for HDR TVs
target-trc=auto
vf=format=colorlevels=full:colormatrix=auto
video-output-levels=full
target-colorspace-hint=yes
hdr-compute-peak=yes
icc-profile-auto=yes
dither-depth=auto
temporal-dither=yes
dither=fruit


# Profiles
[audio-only]
profile-desc="Settings for all audio files"
profile-cond=p["video-format"] == "mjpeg" or p["video-format"] == "png" or (p["estimated-frame-count"] or 0) < 2 or not vid
profile-restore=copy
no-audio-display

# Internet Settings
[protocol.http]
hls-bitrate=max # use max quality for HLS streams
cache=yes
no-cache-pause # don't pause when the cache runs low

[protocol.https]
profile=protocol.http

[protocol.ytdl]
profile=protocol.http
